### ISSUE TITLE
User Poll - View Status Option

### ISSUE THREAD

**Issue by dkelly255** [dkelly255/love-running#1]
In order to **view the current poll status**, as a **user**, I can **select an option to view current poll status**

**Comment by dkelly255** [comment]
Acceptance Criteria:

1. Acceptance Criteria 1: The user can click a button to view the current poll status
2. Acceptance Criteria 2: When clicked, the button operates correctly

**Comment by dkelly255** [comment]
# Tasks:

- [ ] Add the HTML/CSS code for a button
- [ ] Name the button "View current poll status" 
- [ ] Use Javascript to display a snapshot of the current votes per option on the poll
