### ISSUE TITLE
User Poll - Change Original Vote

### ISSUE THREAD

**Issue by dkelly255** [dkelly255/love-running#2]
In order to change my original vote as a user I can choose to change my original vote/selection

**Comment by dkelly255** [comment]
Acceptance Criteria:

- Acceptance Criteria 1: The user can click a button to amend their original poll response
- Acceptance Criteria 2: When clicked, the button operates correctly, removes the users original vote, and allows them to re-vote

**Comment by dkelly255** [comment]
# Tasks:

- [ ]  Add the HTML/CSS code for a button
- [ ]  Name the button "Change Poll Response"
- [ ]  Use Javascript to delete the user's original vote and re-prompt for a new vote
