### ISSUE TITLE
User Poll - Hide poll option

### ISSUE THREAD

**Issue by dkelly255** [dkelly255/love-running#3]
In order to **hide the poll** as a **user**, I can **select an option to hide the poll**

**Comment by dkelly255** [comment]
# Acceptance Criteria:

1. Acceptance Criteria 1: The user can click a button to hide the poll from the screen
2. Acceptance Criteria 2: When clicked, the button operates correctly, hides the poll, and adds another button to unhide the poll

# Tasks

- [ ]  Add the HTML/CSS code for a button
- [ ]  Name the button "Hide User Poll"
- [ ]  Use Javascript to hide the poll, and display another button to unhide the poll
